### ISSUE TITLE
timestamptz

### ISSUE THREAD

**Issue by carlocorradini** [ArsenyYankovsky/typeorm-aurora-data-api-driver#62]
I have several columns that use *timestamptz*, however TypeORM (or the driver or AWS - I really don't know) returns the value without the *'Z'* that represents the correct timezone. The value is treated as a *string* type and not as a *Date* type (normal behaviour) due to (I guess) parsing problems.

**PLEASE SEE [this issue](https://github.com/koxudaxi/local-data-api/issues/106#issuecomment-803398424) from *local-data-api* for more information:**

Me and @koxudaxi are trying to investigate but we need more help...

I've made a test repo to try the strange (error???) behaviour. You can find it [here](https://github.com/carlocorradini/local-data-api-issue).

> After hours of trial and error I've finally discovered another issue (sorry 😅😅😅) that is a little "bit dangerous" since has not been discovered even in the older versions (pre 0.6).
> The value of ```timestamptz (timestamp with timezone)``` (See [this](https://www.postgresql.org/docs/9.1/datatype-datetime.html)) is trimmed after 3 digits (of the ms) removing the 'Z' of the timezone.
> In javascript trying to parse the value without the 'Z' results in a 'string' type rather than a 'Date' type. However this causes undefined behaviour or parsing exceptions in other languages.
> **NB: This problem affect both working and not working versions of docker compose.**
> I've updated the with a new testing procedures (not only for timestamptz): <https://github.com/carlocorradini/local-data-api-issue>
> PS: *timestamp* works 😎

**Any idea or suggestion will be super appreciated!!!**

**Comment by carlocorradini** [comment]
I have tried with the new version (2.0.0) and typeorm fork.

However ```timestamptz``` is treated as a ```string```.

I'm doing my tests with [local-data-api](https://github.com/koxudaxi/local-data-api).

![immagine_2021-03-22_205558](https://user-images.githubusercontent.com/21266147/112050313-00fb1980-8b51-11eb-8fba-f72bfd21ee80.png)

Have you any idea how to solve this? Thanks! 🎉🎊🎉🎊✨

**Comment by ArsenyYankovsky** [comment]
@carlocorradini Could you please add a simple test case and create a PR? I'll take a look at it later this week.

**Comment by carlocorradini** [comment]
> @carlocorradini Could you please add a simple test case and create a PR? I'll take a look at it later this week.

Clone <https://github.com/carlocorradini/local-data-api-issue>

Run ```npm install```

Rub ```npm test```

**Comment by carlocorradini** [comment]
> @carlocorradini Could you please add a simple test case and create a PR? I'll take a look at it later this week.

Can you try the script on a real simple test aurora database?

**Comment by ArsenyYankovsky** [comment]
> > @carlocorradini Could you please add a simple test case and create a PR? I'll take a look at it later this week.
> 
> Can you try the script on a real simple test aurora database to fully understand if is the driver or the local-data-api?
> 
> Thanks again! 🎉

That looks good enough, thanks. Will take a look tomorrow or a day after. I think it's going to be a pretty simple fix.

**Comment by ArsenyYankovsky** [comment]
@carlocorradini I just released a version 2.0.1 with a fix. There's also a new test case for this.

**Comment by carlocorradini** [comment]
> @carlocorradini I just released a version 2.0.1 with a fix. There's also a new test case for this.

Now it's working! Thanks✨🎉!!!

I've a different problem... now with ```timestamp``` that I want to share (<https://github.com/carlocorradini/local-data-api-issue> has been updated if you want to try).

The value of a `timestamp` column retrieved using data-api is different from the one retrieved using direct postgres connection. The difference resides in the time (timezone ????).

I don't know if this is correct or not but since I am on the same machine I think that there are no real timezone problems.

What do you think?

Thanks for your help!

**Comment by ArsenyYankovsky** [comment]
@carlocorradini I released a new version 2.0.2 in which the timestamptz is handled in the same manner as TypeORM Postgres driver handles it. It would be nice to have more test cases regarding date/time types.

**Comment by carlocorradini** [comment]
> @carlocorradini I released a new version 2.0.2 in which the timestamptz is handled in the same manner as TypeORM Postgres driver handles it. It would be nice to have more test cases regarding date/time types.

Thanks for your help.

Now I'm receiving the error with timestamptz where the time is shifted.
```bash
ERROR: User created_at Thu Mar 25 2021 10:11:52 GMT+0100 (GMT+01:00) (type object) is different from UserTimestamptz created_at: Thu Mar 25 2021 11:11:52 GMT+0100 (GMT+01:00) (type object)
```

PS: I'm still receiving the deprecation notice of highlight:
```bash
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
```

**Comment by koxudaxi** [comment]
I add a comment

> Now I'm receiving the error with timestamptz where the time is shifted.

DataAPI always returns Timestamptz as UTC timezone without timezone format.

> For Amazon Aurora PostgreSQL, the Data API always returns the Aurora PostgreSQL datatype TIMESTAMPTZ in UTC timezone.
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html

**Comment by ArsenyYankovsky** [comment]
The warning is coming from the TypeORM code, so nothing I can do there.
The timestamptz timezone is remove so the original code was correct it seems. You can still use the 2.0.1 then to get a correct result.
I will make proper fixes and add test cases based on data api documentation later this week when I have time.

**Comment by carlocorradini** [comment]
> I add a comment
> 
> > Now I'm receiving the error with timestamptz where the time is shifted.
> 
> DataAPI always returns Timestamptz as UTC timezone without timezone format.
> 
> > For Amazon Aurora PostgreSQL, the Data API always returns the Aurora PostgreSQL datatype TIMESTAMPTZ in UTC timezone.
> > https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html

Thanks for your help.
Unfortunately I cannot directly test on a real Aurora Database so your help is really precious!

**Comment by carlocorradini** [comment]
> > I add a comment
> > > Now I'm receiving the error with timestamptz where the time is shifted.
> > 
> > 
> > DataAPI always returns Timestamptz as UTC timezone without timezone format.
> > > For Amazon Aurora PostgreSQL, the Data API always returns the Aurora PostgreSQL datatype TIMESTAMPTZ in UTC timezone.
> > > https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html
> 
> Thanks for your help.
> Unfortunately I cannot directly test on a real Aurora Database so your help is really precious!

Thanks again @ArsenyYankovsky !!!!!!!

**Comment by ArsenyYankovsky** [comment]
You don't have to use my fork anymore since new TypeORM 0.3.32 was released. Feel free to comment here or open a new issue if something doesn't work.
